### PR TITLE
Improve compatibility with original Twig version

### PR DESCRIPTION
**Pull request by thomashunziker**
Add features to increase the compatibility with the original Twig implementation in PHP and with JTwig. Beside those improvements I change some small stuff to allow better extensibility by other developers. I hope my commit messages are clear enough. 

I appreciate any feedback.

### CODE REVIEW

**Comment by mbosecke** [comment]
Hey man, this is all really great stuff. I'm loving it.

I am having one problem though. The unit tests work perfectly on my linux machine but all of the ones in TestRelativePath fail on my windows machine. The loaders can't seem to be able to find the templates. Here's an example stack trace:

    com.mitchellbosecke.pebble.error.LoaderException: Could not find template "./template.relativeinclude2.peb" (?:?)

	at com.mitchellbosecke.pebble.loader.DelegatingLoader.getReader(DelegatingLoader.java:68)
	at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:217)
	at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:206)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at com.mitchellbosecke.pebble.PebbleEngine.getTemplate(PebbleEngine.java:206)
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.includeTemplate(PebbleTemplateImpl.java:164)
	at com.mitchellbosecke.pebble.node.IncludeNode.render(IncludeNode.java:52)
	at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
	at com.mitchellbosecke.pebble.node.RootNode.render(RootNode.java:32)
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.buildContent(PebbleTemplateImpl.java:62)
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:112)
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:72)
	at com.mitchellbosecke.pebble.TestRelativePath.testRelativeInclude(TestRelativePath.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by thomashunziker** [comment]
The last commit should fix the issue with the separator for windows.

**Comment by thomashunziker** [comment]
Hi Mitchell,
We gone use pebble for one of our projects. However we have specific requirements regarding the handling of templates. Our users will be able to edit the templates and hence we need to tweak pebble a bit for our use case. I will provide all changes back here. Please give me any feedback on the changes. I'am very interested to push back our changes to your project!

Regards,
Thomas

**Comment by mbosecke** [comment]
I merged a bunch of these commits but I'm a little confused on 8bcaf4e. The cache system does not cache the output of the templates and therefore I can't think of a reason why we need to be able to provide extra contextual information when retrieving a template from the cache. The template itself is generic. What is a use case for this?

**Comment by thomashunziker** [comment]
The cache does store the 'compiled' template. When the determination of the template source depends on the context the cache key needs to be adapted.

Use cases:
* The user can select a theme. Based on the theme different template files are used. When the theme is not part of the cache key, then you will load for /templates/my-theme/sample.peb the same compiled template as /templates/other-theme/sample.peb. This is because in such situations you will modify the prefix of the template rather than add to each template the full path. Currently the suffix and the prefix are not part of the cache key.
*  Content management system as SaaS: Another use case is when you allow your users to provide their own templates. E.g. each user can provide another template for the contact form. Depending on the context (e.g. domain) you select a different template. Since you want to provide an out of the box solution you provide default templates. E.g. the user can optionally override certain templates. These means the PebbleEngine contains two loaders one for the user specified templates and one for the default templates. The loader for the default templates takes over when the user has not provide a template.

In both cases you can argue that one of the following solution can be applied:

1. Add the context to the template name. e.g. including the theme name / the user id in the template name.
2. You create for each context (e.g. theme / user) a dedicated cache.

I think both solution are not working:

1. Solution: When you need to add the context to the template name the templates will depend on the context. E.g. each user needs to add the user id to the include, extends and import statements. Actually the templates get context dependent. This is not optimal, because when the context changes all templates needs to be changed. E.g. a renaming of the theme requires to change all include, extends and import statements.
2. Solution: Since you cannot have multiple caches per PebbleEngine you need to create for each context a dedicated PebbleEngine. In the second use case this creates a overhead because you need to store the default templates per user and you cannot share the compiled template between the users.

Its easy to break the current system: When you change the prefix on a FileLoader without resetting the cache on the PebbleEngine and you change the prefix in a way that the new path leads to the same template file structure with different template content, the PebbleEngine will use the old templates.

I hope my explanations are clear. I'm glade to answer any further questions regarding the topic.

**Comment by mbosecke** [comment]
Thanks for the detailed response. That makes sense, and I'm glad to include the contribution. 

Thanks again for all of your work. I'll try to release the next official version of Pebble this week.

**Pull request closed without merging**
